[package]
name = "rust_study" # 这个名称是crate.io上的唯一标识
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.dev]
opt-level = 0 # 不对编译进行优化

[profile.release]
opt-level = 3 # 对编译进行最高程度的优化
